This notebook provides recipes for loading and saving data from external sources.

In [ ]:
!pip install  torch
!pip install matplotlib
!pip install numpy
!pip install pandas

  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.3/21

# Base Structure of training NN

Define Model or network

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim


# Define the model
class MyModel(nn.Module):
  def __init__(self):
    super(MyModel, self).__init__()
    self.linear = nn.Linear(10, 10)
    self.linear1 = nn.Linear(10, 1)

  def forward(self, x):
    y=self.linear(x)
    y=torch.sigmoid(y)
    y=self.linear1(y)
    return(y)



#Model and Data

In [ ]:
# Initialize the model
model = MyModel()
optimizer = optim.SGD(model.parameters(), lr=0.01)
#optimizer=optim.Adagrad(model.parameters(), lr=0.01)
# Generate random input and output
X = torch.randn(1000, 10)
Y_gt = torch.randn(1000, 1)


In [ ]:
Y_gt

#Dig Down

In [ ]:
# model  trainable parameters with name ans shape
for name, param in model.named_parameters():
    if param.requires_grad:
        print(name, param.shape,print(param))

Parameter containing:
tensor([[ 0.1515, -0.2060,  0.2242,  0.1469, -0.2166, -0.2497,  0.2416,  0.1558,
         -0.3129, -0.1736],
        [ 0.1883,  0.2418,  0.0876, -0.2656,  0.1930, -0.1413, -0.1376, -0.0699,
         -0.0965,  0.1730],
        [-0.1406, -0.1437, -0.3132,  0.0466, -0.1108, -0.0416, -0.1788, -0.2457,
          0.0701,  0.2687],
        [ 0.1052, -0.0728,  0.1676,  0.2454,  0.0751, -0.0160,  0.0234,  0.1863,
         -0.2692,  0.0563],
        [-0.2706, -0.2320,  0.1427,  0.1438, -0.3001, -0.1119, -0.2097, -0.1735,
          0.1802,  0.0049],
        [ 0.1598,  0.2397,  0.0598, -0.2908, -0.2517, -0.2000, -0.0806, -0.0339,
          0.2793, -0.1497],
        [ 0.2282, -0.1376,  0.1262, -0.1929, -0.3063, -0.2974, -0.0092, -0.0024,
          0.0389, -0.2756],
        [ 0.1309, -0.2427, -0.1736, -0.2193, -0.1966, -0.1765, -0.1338, -0.2739,
          0.1321, -0.1609],
        [-0.1087,  0.1503,  0.0581, -0.1996,  0.0935, -0.1298,  0.2114, -0.2799,
         -0.0426,  0.0395

In [ ]:
X.shape

torch.Size([1000, 10])

**Forward and Backward pass**

In [ ]:
#Forward Pass
Y=model(X)

# Backward pass
loss=torch.mean(torch.abs(Y-Y_gt))
optimizer.zero_grad()
loss.backward()
optimizer.step()

In [ ]:
Y=model(X)
print("input shape: ",X.shape)
print("ouput Shape",Y.shape)
print(torch.max(Y))

input shape:  torch.Size([1000, 10])
ouput Shape torch.Size([1000, 1])
tensor(0.6573, grad_fn=<MaxBackward1>)


#Training Loop#

In [ ]:
for  e_idx in range(1000):
  Y=model(X)

  loss=torch.mean(torch.abs(Y-Y_gt))

  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  # model  trainable parameters with name ans shape
  for name, param in model.named_parameters():
      if param.requires_grad:
          print(name, param.shape,print(param))


  if  e_idx%10==0:
    print(f"epoch {e_idx} loss {loss.item()}")

Streaming output truncated to the last 5000 lines.
tensor([-0.2110], requires_grad=True)
linear1.bias torch.Size([1]) None
Parameter containing:
tensor([[ 0.1523, -0.1859,  0.2347,  0.1356, -0.2093, -0.2535,  0.2215,  0.1502,
         -0.3104, -0.1787],
        [ 0.1780,  0.2803,  0.1197, -0.2834,  0.2146, -0.1474, -0.1795, -0.0840,
         -0.0805,  0.1504],
        [-0.1389, -0.1200, -0.3013,  0.0313, -0.0983, -0.0418, -0.2048, -0.2536,
          0.0765,  0.2602],
        [ 0.1033, -0.0464,  0.1836,  0.2289,  0.0882, -0.0193, -0.0057,  0.1738,
         -0.2647,  0.0465],
        [-0.2646, -0.2824,  0.0952,  0.1817, -0.3261, -0.1081, -0.1532, -0.1421,
          0.1666,  0.0365],
        [ 0.1580,  0.2419,  0.0621, -0.2911, -0.2504, -0.2002, -0.0836, -0.0352,
          0.2793, -0.1510],
        [ 0.2212, -0.1069,  0.1427, -0.2105, -0.2892, -0.3000, -0.0406, -0.0181,
          0.0425, -0.2861],
        [ 0.1364, -0.2855, -0.1978, -0.1948, -0.2168, -0.1704, -0.0898, -0.2467,
          0

In [ ]:
x.numpy()